// src/owo_data.js

export const ANIMALS = {
  common: [
    { name: "Mouse", emoji: "🐭", exp: 10, value: 5, rarity: "Common" },
    { name: "Rabbit", emoji: "🐰", exp: 12, value: 6, rarity: "Common" },
    { name: "Duck", emoji: "🦆", exp: 15, value: 8, rarity: "Common" },
    { name: "Chicken", emoji: "🐔", exp: 15, value: 8, rarity: "Common" },
    { name: "Pig", emoji: "🐷", exp: 18, value: 10, rarity: "Common" },
    { name: "Cow", emoji: "🐮", exp: 20, value: 12, rarity: "Common" },
    { name: "Sheep", emoji: "🐑", exp: 20, value: 12, rarity: "Common" },
    { name: "Goat", emoji: "🐐", exp: 22, value: 14, rarity: "Common" },
    { name: "Dog", emoji: "🐶", exp: 24, value: 15, rarity: "Common" },
    { name: "Cat", emoji: "🐱", exp: 24, value: 15, rarity: "Common" },
    { name: "Horse", emoji: "🐴", exp: 26, value: 18, rarity: "Common" },
    { name: "Donkey", emoji: "🫏", exp: 26, value: 18, rarity: "Common" },
    { name: "Hamster", emoji: "🐹", exp: 12, value: 8, rarity: "Common" },
    { name: "Guinea Pig", emoji: "🐹", exp: 14, value: 9, rarity: "Common" },
    { name: "Turkey", emoji: "🦃", exp: 28, value: 20, rarity: "Common" }
  ],
  uncommon: [
    { name: "Fox", emoji: "🦊", exp: 25, value: 20, rarity: "Uncommon" },
    { name: "Deer", emoji: "🦌", exp: 30, value: 25, rarity: "Uncommon" },
    { name: "Raccoon", emoji: "🦝", exp: 35, value: 30, rarity: "Uncommon" },
    { name: "Squirrel", emoji: "🐿️", exp: 35, value: 30, rarity: "Uncommon" },
    { name: "Owl", emoji: "🦉", exp: 40, value: 35, rarity: "Uncommon" },
    { name: "Badger", emoji: "🦡", exp: 42, value: 38, rarity: "Uncommon" },
    { name: "Beaver", emoji: "🦫", exp: 45, value: 40, rarity: "Uncommon" },
    { name: "Hedgehog", emoji: "🦔", exp: 45, value: 40, rarity: "Uncommon" },
    { name: "Skunk", emoji: "🦨", exp: 48, value: 42, rarity: "Uncommon" },
    { name: "Otter", emoji: "🦦", exp: 50, value: 45, rarity: "Uncommon" },
    { name: "Weasel", emoji: "🦦", exp: 50, value: 45, rarity: "Uncommon" },
    { name: "Bat", emoji: "🦇", exp: 52, value: 48, rarity: "Uncommon" },
    { name: "Frog", emoji: "🐸", exp: 30, value: 25, rarity: "Uncommon" },
    { name: "Toad", emoji: "🐸", exp: 32, value: 26, rarity: "Uncommon" },
    { name: "Lizard", emoji: "🦎", exp: 34, value: 28, rarity: "Uncommon" }
  ],
  rare: [
    { name: "Lion", emoji: "🦁", exp: 60, value: 75, rarity: "Rare" },
    { name: "Tiger", emoji: "🐯", exp: 65, value: 80, rarity: "Rare" },
    { name: "Leopard", emoji: "🐆", exp: 70, value: 85, rarity: "Rare" },
    { name: "Cheetah", emoji: "🐆", exp: 75, value: 90, rarity: "Rare" },
    { name: "Jaguar", emoji: "🐈", exp: 80, value: 100, rarity: "Rare" },
    { name: "Bear", emoji: "🐻", exp: 85, value: 110, rarity: "Rare" },
    { name: "Wolf", emoji: "🐺", exp: 85, value: 110, rarity: "Rare" },
    { name: "Coyote", emoji: "🐺", exp: 88, value: 115, rarity: "Rare" },
    { name: "Hyena", emoji: "🐆", exp: 90, value: 120, rarity: "Rare" },
    { name: "Gorilla", emoji: "🦍", exp: 95, value: 130, rarity: "Rare" },
    { name: "Chimpanzee", emoji: "🦧", exp: 92, value: 125, rarity: "Rare" },
    { name: "Orangutan", emoji: "🦧", exp: 94, value: 128, rarity: "Rare" },
    { name: "Baboon", emoji: "🦍", exp: 96, value: 132, rarity: "Rare" },
    { name: "Panda", emoji: "🐼", exp: 100, value: 150, rarity: "Rare" },
    { name: "Koala", emoji: "🐨", exp: 80, value: 100, rarity: "Rare" }
  ],
  epic: [
    { name: "Dragon", emoji: "🐉", exp: 150, value: 250, rarity: "Epic" },
    { name: "Unicorn", emoji: "🦄", exp: 160, value: 280, rarity: "Epic" },
    { name: "Phoenix", emoji: "🐦", exp: 180, value: 300, rarity: "Epic" },
    { name: "Griffin", emoji: "🦅", exp: 190, value: 320, rarity: "Epic" },
    { name: "Chimera", emoji: "🦁", exp: 200, value: 350, rarity: "Epic" },
    { name: "Pegasus", emoji: "🦄", exp: 210, value: 380, rarity: "Epic" },
    { name: "Hippogriff", emoji: "🦅", exp: 220, value: 400, rarity: "Epic" },
    { name: "Basilisk", emoji: "🐍", exp: 230, value: 420, rarity: "Epic" },
    { name: "Hydra", emoji: "🐉", exp: 240, value: 450, rarity: "Epic" },
    { name: "Cerberus", emoji: "🐕", exp: 250, value: 480, rarity: "Epic" },
    { name: "Minotaur", emoji: "🐂", exp: 210, value: 370, rarity: "Epic" },
    { name: "Sphinx", emoji: "🦁", exp: 220, value: 390, rarity: "Epic" },
    { name: "Wyvern", emoji: "🐉", exp: 235, value: 410, rarity: "Epic" },
    { name: "Cockatrice", emoji: "🐔", exp: 245, value: 440, rarity: "Epic" },
    { name: "Thunderbird", emoji: "🦅", exp: 250, value: 500, rarity: "Epic" }
  ],
  mythic: [
    { name: "Kraken", emoji: "🦑", exp: 400, value: 800, rarity: "Mythic" },
    { name: "Leviathan", emoji: "🐉", exp: 450, value: 900, rarity: "Mythic" },
    { name: "Bahamut", emoji: "🐲", exp: 500, value: 1000, rarity: "Mythic" },
    { name: "Tiamat", emoji: "🐉", exp: 550, value: 1100, rarity: "Mythic" },
    { name: "Cthulhu", emoji: "🐙", exp: 600, value: 1200, rarity: "Mythic" },
    { name: "Poseidon", emoji: "🔱", exp: 620, value: 1250, rarity: "Mythic" },
    { name: "Neptune", emoji: "🔱", exp: 620, value: 1250, rarity: "Mythic" },
    { name: "Fenrir", emoji: "🐺", exp: 650, value: 1300, rarity: "Mythic" },
    { name: "Jormungandr", emoji: "🐍", exp: 680, value: 1400, rarity: "Mythic" },
    { name: "Behemoth", emoji: "🐘", exp: 700, value: 1500, rarity: "Mythic" },
    { name: "Ziz", emoji: "🦅", exp: 660, value: 1350, rarity: "Mythic" },
    { name: "Yamata no Orochi", emoji: "🐍", exp: 720, value: 1600, rarity: "Mythic" },
    { name: "Quetzalcoatl", emoji: "🐍", exp: 690, value: 1450, rarity: "Mythic" },
    { name: "Nidhogg", emoji: "🐉", exp: 710, value: 1550, rarity: "Mythic" },
    { name: "Anubis", emoji: "🐕", exp: 650, value: 1300, rarity: "Mythic" }
  ],
  legendary: [
    { name: "Arceus", emoji: "🌟", exp: 1000, value: 2500, rarity: "Legendary" },
    { name: "Mewtwo", emoji: "🔮", exp: 1100, value: 2700, rarity: "Legendary" },
    { name: "Kyogre", emoji: "🐳", exp: 1200, value: 3000, rarity: "Legendary" },
    { name: "Groudon", emoji: "🌋", exp: 1300, value: 3200, rarity: "Legendary" },
    { name: "Rayquaza", emoji: "🐉", exp: 1500, value: 4000, rarity: "Legendary" },
    { name: "Dialga", emoji: "⏳", exp: 1400, value: 3500, rarity: "Legendary" },
    { name: "Palkia", emoji: "🌌", exp: 1400, value: 3500, rarity: "Legendary" },
    { name: "Giratina", emoji: "👻", exp: 1450, value: 3700, rarity: "Legendary" },
    { name: "Reshiram", emoji: "🔥", exp: 1500, value: 4000, rarity: "Legendary" },
    { name: "Zekrom", emoji: "⚡", exp: 1500, value: 4000, rarity: "Legendary" },
    { name: "Kyurem", emoji: "❄️", exp: 1550, value: 4200, rarity: "Legendary" },
    { name: "Xerneas", emoji: "🦌", exp: 1600, value: 4500, rarity: "Legendary" },
    { name: "Yveltal", emoji: "🦅", exp: 1600, value: 4500, rarity: "Legendary" },
    { name: "Solgaleo", emoji: "🦁", exp: 1700, value: 5000, rarity: "Legendary" },
    { name: "Lunala", emoji: "🦇", exp: 1700, value: 5000, rarity: "Legendary" }
  ],
  special: [
    { name: "Halloween Ghost", emoji: "👻", exp: 800, value: 2000, rarity: "Special" },
    { name: "Christmas Reindeer", emoji: "🦌", exp: 850, value: 2100, rarity: "Special" },
    { name: "Cupid Angel", emoji: "👼", exp: 900, value: 2200, rarity: "Special" },
    { name: "Easter Egg", emoji: "🥚", exp: 950, value: 2300, rarity: "Special" },
    { name: "Summer Shark", emoji: "🦈", exp: 850, value: 2150, rarity: "Special" },
    { name: "Vampire Bat", emoji: "🦇", exp: 880, value: 2200, rarity: "Special" },
    { name: "Werewolf", emoji: "🐺", exp: 900, value: 2250, rarity: "Special" },
    { name: "Witch Cat", emoji: "🐈", exp: 920, value: 2300, rarity: "Special" },
    { name: "Zombie Dog", emoji: "🐕", exp: 920, value: 2300, rarity: "Special" },
    { name: "Mummy Cat", emoji: "🐈", exp: 940, value: 2350, rarity: "Special" },
    { name: "Leprechaun", emoji: "🍀", exp: 950, value: 2400, rarity: "Special" },
    { name: "Cupid", emoji: "💘", exp: 960, value: 2450, rarity: "Special" },
    { name: "Jack o Lantern", emoji: "🎃", exp: 970, value: 2500, rarity: "Special" },
    { name: "Snowman", emoji: "⛄", exp: 800, value: 2000, rarity: "Special" },
    { name: "Thanksgiving Turkey", emoji: "🦃", exp: 850, value: 2100, rarity: "Special" }
  ]
};

export const WEAPONS = [
  // Bronze Tier
  { id: "bronze_sword", name: "Bronze Sword", tier: "Bronze", price: 100, dmg: 10, accuracy: 0.85, durability: 20 },
  { id: "bronze_dagger", name: "Bronze Dagger", tier: "Bronze", price: 80, dmg: 8, accuracy: 0.95, durability: 15 },
  { id: "bronze_spear", name: "Bronze Spear", tier: "Bronze", price: 120, dmg: 12, accuracy: 0.88, durability: 25 },
  { id: "bronze_mace", name: "Bronze Mace", tier: "Bronze", price: 130, dmg: 15, accuracy: 0.80, durability: 22 },
  { id: "bronze_axe", name: "Bronze Axe", tier: "Bronze", price: 150, dmg: 18, accuracy: 0.75, durability: 20 },
  { id: "bronze_bow", name: "Bronze Bow", tier: "Bronze", price: 140, dmg: 11, accuracy: 0.90, durability: 30 },
  { id: "bronze_shield", name: "Bronze Shield", tier: "Bronze", price: 110, dmg: 5, accuracy: 0.80, durability: 40 },
  { id: "bronze_rapier", name: "Bronze Rapier", tier: "Bronze", price: 160, dmg: 14, accuracy: 0.92, durability: 18 },
  { id: "bronze_saber", name: "Bronze Saber", tier: "Bronze", price: 170, dmg: 16, accuracy: 0.87, durability: 21 },
  { id: "bronze_club", name: "Bronze Club", tier: "Bronze", price: 90, dmg: 11, accuracy: 0.78, durability: 25 },

  // Iron Tier
  { id: "iron_sword", name: "Iron Sword", tier: "Iron", price: 250, dmg: 22, accuracy: 0.85, durability: 35 },
  { id: "iron_dagger", name: "Iron Dagger", tier: "Iron", price: 200, dmg: 17, accuracy: 0.95, durability: 30 },
  { id: "iron_spear", name: "Iron Spear", tier: "Iron", price: 280, dmg: 25, accuracy: 0.88, durability: 40 },
  { id: "iron_mace", name: "Iron Mace", tier: "Iron", price: 300, dmg: 30, accuracy: 0.80, durability: 35 },
  { id: "iron_axe", name: "Iron Axe", tier: "Iron", price: 320, dmg: 35, accuracy: 0.75, durability: 32 },
  { id: "iron_bow", name: "Iron Bow", tier: "Iron", price: 310, dmg: 24, accuracy: 0.90, durability: 45 },
  { id: "iron_claymore", name: "Iron Claymore", tier: "Iron", price: 380, dmg: 40, accuracy: 0.72, durability: 28 },
  { id: "iron_scimitar", name: "Iron Scimitar", tier: "Iron", price: 270, dmg: 21, accuracy: 0.88, durability: 38 },
  { id: "iron_warhammer", name: "Iron Warhammer", tier: "Iron", price: 350, dmg: 38, accuracy: 0.78, durability: 30 },
  { id: "iron_halberd", name: "Iron Halberd", tier: "Iron", price: 400, dmg: 45, accuracy: 0.80, durability: 42 },

  // Steel Tier
  { id: "steel_sword", name: "Steel Sword", tier: "Steel", price: 500, dmg: 48, accuracy: 0.85, durability: 50 },
  { id: "steel_dagger", name: "Steel Dagger", tier: "Steel", price: 450, dmg: 38, accuracy: 0.95, durability: 45 },
  { id: "steel_spear", name: "Steel Spear", tier: "Steel", price: 550, dmg: 52, accuracy: 0.88, durability: 60 },
  { id: "steel_mace", name: "Steel Mace", tier: "Steel", price: 580, dmg: 60, accuracy: 0.80, durability: 55 },
  { id: "steel_axe", name: "Steel Axe", tier: "Steel", price: 620, dmg: 70, accuracy: 0.75, durability: 50 },
  { id: "steel_bow", name: "Steel Bow", tier: "Steel", price: 600, dmg: 50, accuracy: 0.90, durability: 70 },
  { id: "steel_halberd", name: "Steel Halberd", tier: "Steel", price: 700, dmg: 85, accuracy: 0.80, durability: 65 },
  { id: "steel_longsword", name: "Steel Longsword", tier: "Steel", price: 550, dmg: 55, accuracy: 0.85, durability: 52 },
  { id: "steel_flail", name: "Steel Flail", tier: "Steel", price: 590, dmg: 62, accuracy: 0.78, durability: 58 },
  { id: "steel_bardiche", name: "Steel Bardiche", tier: "Steel", price: 680, dmg: 80, accuracy: 0.76, durability: 60 },

  // Silver Tier
  { id: "silver_sword", name: "Silver Sword", tier: "Silver", price: 1000, dmg: 85, accuracy: 0.85, durability: 75 },
  { id: "silver_rapier", name: "Silver Rapier", tier: "Silver", price: 950, dmg: 75, accuracy: 0.95, durability: 65 },
  { id: "silver_spear", name: "Silver Spear", tier: "Silver", price: 1100, dmg: 92, accuracy: 0.88, durability: 90 },
  { id: "silver_mace", name: "Silver Mace", tier: "Silver", price: 1150, dmg: 105, accuracy: 0.80, durability: 80 },
  { id: "silver_axe", name: "Silver Axe", tier: "Silver", price: 1200, dmg: 120, accuracy: 0.75, durability: 70 },
  { id: "silver_longbow", name: "Silver Longbow", tier: "Silver", price: 1180, dmg: 88, accuracy: 0.92, durability: 100 },
  { id: "silver_halberd", name: "Silver Halberd", tier: "Silver", price: 1300, dmg: 140, accuracy: 0.80, durability: 85 },
  { id: "silver_dagger", name: "Silver Dagger", tier: "Silver", price: 900, dmg: 70, accuracy: 0.96, durability: 70 },
  { id: "silver_warclaw", name: "Silver Warclaw", tier: "Silver", price: 1050, dmg: 90, accuracy: 0.90, durability: 75 },
  { id: "silver_shield", name: "Silver Shield", tier: "Silver", price: 950, dmg: 40, accuracy: 0.82, durability: 150 },

  // Gold Tier
  { id: "gold_sword", name: "Gold Sword", tier: "Gold", price: 2500, dmg: 180, accuracy: 0.85, durability: 110 },
  { id: "gold_dagger", name: "Gold Dagger", tier: "Gold", price: 2200, dmg: 150, accuracy: 0.95, durability: 95 },
  { id: "gold_spear", name: "Gold Spear", tier: "Gold", price: 2700, dmg: 195, accuracy: 0.88, durability: 130 },
  { id: "gold_scepter", name: "Gold Scepter", tier: "Gold", price: 3200, dmg: 220, accuracy: 0.85, durability: 120 },
  { id: "gold_axe", name: "Gold Axe", tier: "Gold", price: 3000, dmg: 250, accuracy: 0.75, durability: 100 },
  { id: "gold_bow", name: "Gold Bow", tier: "Gold", price: 2900, dmg: 185, accuracy: 0.90, durability: 140 },
  { id: "gold_greatsword", name: "Gold Greatsword", tier: "Gold", price: 3500, dmg: 300, accuracy: 0.70, durability: 90 },
  { id: "gold_gladius", name: "Gold Gladius", tier: "Gold", price: 2600, dmg: 182, accuracy: 0.88, durability: 112 },
  { id: "gold_morningstar", name: "Gold Morningstar", tier: "Gold", price: 2800, dmg: 210, accuracy: 0.80, durability: 115 },
  { id: "gold_katana", name: "Gold Katana", tier: "Gold", price: 3400, dmg: 240, accuracy: 0.92, durability: 105 },

  // Ruby Tier
  { id: "ruby_sword", name: "Ruby Sword", tier: "Ruby", price: 6000, dmg: 400, accuracy: 0.85, durability: 180 },
  { id: "ruby_dagger", name: "Ruby Dagger", tier: "Ruby", price: 5500, dmg: 350, accuracy: 0.95, durability: 160 },
  { id: "ruby_glaive", name: "Ruby Glaive", tier: "Ruby", price: 6500, dmg: 440, accuracy: 0.88, durability: 200 },
  { id: "ruby_warhammer", name: "Ruby Warhammer", tier: "Ruby", price: 7000, dmg: 500, accuracy: 0.80, durability: 190 },
  { id: "ruby_battleaxe", name: "Ruby Battleaxe", tier: "Ruby", price: 7500, dmg: 580, accuracy: 0.75, durability: 170 },
  { id: "ruby_recurve", name: "Ruby Recurve", tier: "Ruby", price: 7200, dmg: 420, accuracy: 0.90, durability: 220 },
  { id: "ruby_claymore", name: "Ruby Claymore", tier: "Ruby", price: 8000, dmg: 680, accuracy: 0.72, durability: 150 },
  { id: "ruby_rapier", name: "Ruby Rapier", tier: "Ruby", price: 6200, dmg: 390, accuracy: 0.94, durability: 175 },
  { id: "ruby_scythe", name: "Ruby Scythe", tier: "Ruby", price: 7800, dmg: 620, accuracy: 0.76, durability: 185 },
  { id: "ruby_shield", name: "Ruby Shield", tier: "Ruby", price: 6000, dmg: 150, accuracy: 0.80, durability: 350 },

  // Emerald Tier
  { id: "emerald_dagger", name: "Emerald Dagger", tier: "Emerald", price: 12000, dmg: 600, accuracy: 0.95, durability: 220 },
  { id: "emerald_sword", name: "Emerald Sword", tier: "Emerald", price: 13000, dmg: 700, accuracy: 0.85, durability: 250 },
  { id: "emerald_spear", name: "Emerald Spear", tier: "Emerald", price: 14000, dmg: 780, accuracy: 0.88, durability: 280 },
  { id: "emerald_mace", name: "Emerald Mace", tier: "Emerald", price: 14500, dmg: 850, accuracy: 0.80, durability: 260 },
  { id: "emerald_axe", name: "Emerald Axe", tier: "Emerald", price: 15000, dmg: 950, accuracy: 0.75, durability: 240 },
  { id: "emerald_shortbow", name: "Emerald Shortbow", tier: "Emerald", price: 13500, dmg: 720, accuracy: 0.92, durability: 300 },
  { id: "emerald_staff", name: "Emerald Staff", tier: "Emerald", price: 16000, dmg: 1050, accuracy: 0.85, durability: 270 },
  { id: "emerald_blade", name: "Emerald Blade", tier: "Emerald", price: 13200, dmg: 710, accuracy: 0.86, durability: 255 },
  { id: "emerald_halberd", name: "Emerald Halberd", tier: "Emerald", price: 15500, dmg: 1000, accuracy: 0.78, durability: 265 },
  { id: "emerald_crest", name: "Emerald Crest", tier: "Emerald", price: 12500, dmg: 300, accuracy: 0.82, durability: 450 },

  // Diamond Tier
  { id: "diamond_sword", name: "Diamond Sword", tier: "Diamond", price: 20000, dmg: 1100, accuracy: 0.85, durability: 350 },
  { id: "diamond_katana", name: "Diamond Katana", tier: "Diamond", price: 22000, dmg: 1250, accuracy: 0.92, durability: 320 },
  { id: "diamond_spear", name: "Diamond Spear", tier: "Diamond", price: 21000, dmg: 1180, accuracy: 0.88, durability: 400 },
  { id: "diamond_flail", name: "Diamond Flail", tier: "Diamond", price: 23000, dmg: 1350, accuracy: 0.80, durability: 380 },
  { id: "diamond_greataxe", name: "Diamond Greataxe", tier: "Diamond", price: 25000, dmg: 1550, accuracy: 0.75, durability: 330 },
  { id: "diamond_longbow", name: "Diamond Longbow", tier: "Diamond", price: 24000, dmg: 1200, accuracy: 0.90, durability: 420 },
  { id: "diamond_halberd", name: "Diamond Halberd", tier: "Diamond", price: 26000, dmg: 1650, accuracy: 0.78, durability: 360 },
  { id: "diamond_dagger", name: "Diamond Dagger", tier: "Diamond", price: 19000, dmg: 980, accuracy: 0.96, durability: 310 },
  { id: "diamond_aegis", name: "Diamond Aegis", tier: "Diamond", price: 21500, dmg: 450, accuracy: 0.80, durability: 600 },
  { id: "diamond_glaive", name: "Diamond Glaive", tier: "Diamond", price: 23500, dmg: 1300, accuracy: 0.86, durability: 370 },

  // Obsidian Tier
  { id: "obsidian_blade", name: "Obsidian Blade", tier: "Obsidian", price: 40000, dmg: 2200, accuracy: 0.85, durability: 450 },
  { id: "obsidian_dagger", name: "Obsidian Dagger", tier: "Obsidian", price: 38000, dmg: 1900, accuracy: 0.95, durability: 400 },
  { id: "obsidian_pike", name: "Obsidian Pike", tier: "Obsidian", price: 42000, dmg: 2350, accuracy: 0.88, durability: 500 },
  { id: "obsidian_maul", name: "Obsidian Maul", tier: "Obsidian", price: 45000, dmg: 2700, accuracy: 0.80, durability: 480 },
  { id: "obsidian_cleaver", name: "Obsidian Cleaver", tier: "Obsidian", price: 48000, dmg: 3100, accuracy: 0.75, durability: 420 },
  { id: "obsidian_greatbow", name: "Obsidian Greatbow", tier: "Obsidian", price: 46000, dmg: 2400, accuracy: 0.90, durability: 550 },
  { id: "obsidian_scythe", name: "Obsidian Scythe", tier: "Obsidian", price: 50000, dmg: 3400, accuracy: 0.76, durability: 460 },
  { id: "obsidian_reaver", name: "Obsidian Reaver", tier: "Obsidian", price: 43000, dmg: 2300, accuracy: 0.86, durability: 440 },
  { id: "obsidian_stave", name: "Obsidian Stave", tier: "Obsidian", price: 47000, dmg: 2800, accuracy: 0.84, durability: 470 },
  { id: "obsidian_bulwark", name: "Obsidian Bulwark", tier: "Obsidian", price: 41000, dmg: 800, accuracy: 0.80, durability: 800 },

  // Mythic Tier
  { id: "mythic_calibur", name: "Mythic Calibur", tier: "Mythic", price: 80000, dmg: 4800, accuracy: 0.95, durability: 600 },
  { id: "mythic_dagger", name: "Mythic Dagger", tier: "Mythic", price: 75000, dmg: 4200, accuracy: 0.98, durability: 550 },
  { id: "mythic_spear", name: "Mythic Spear", tier: "Mythic", price: 82000, dmg: 5100, accuracy: 0.90, durability: 680 },
  { id: "mythic_hammer", name: "Mythic Hammer", tier: "Mythic", price: 88000, dmg: 5900, accuracy: 0.82, durability: 650 },
  { id: "mythic_scythe", name: "Mythic Scythe", tier: "Mythic", price: 95000, dmg: 6800, accuracy: 0.78, durability: 620 },
  { id: "mythic_bow", name: "Mythic Bow", tier: "Mythic", price: 86000, dmg: 4900, accuracy: 0.92, durability: 720 },
  { id: "mythic_staff", name: "Mythic Staff", tier: "Mythic", price: 92000, dmg: 6100, accuracy: 0.88, durability: 660 },
  { id: "mythic_claymore", name: "Mythic Claymore", tier: "Mythic", price: 90000, dmg: 6300, accuracy: 0.74, durability: 600 },
  { id: "mythic_lance", name: "Mythic Lance", tier: "Mythic", price: 84000, dmg: 5000, accuracy: 0.88, durability: 670 },
  { id: "mythic_aegis", name: "Mythic Aegis", tier: "Mythic", price: 78000, dmg: 1500, accuracy: 0.80, durability: 1000 },

  // Cosmic Tier
  { id: "cosmic_blade", name: "Cosmic Blade", tier: "Cosmic", price: 150000, dmg: 9900, accuracy: 0.95, durability: 1000 },
  { id: "cosmic_dagger", name: "Cosmic Dagger", tier: "Cosmic", price: 140000, dmg: 8800, accuracy: 0.98, durability: 900 },
  { id: "cosmic_lance", name: "Cosmic Lance", tier: "Cosmic", price: 160000, dmg: 10500, accuracy: 0.90, durability: 1100 },
  { id: "cosmic_destroyer", name: "Cosmic Destroyer", tier: "Cosmic", price: 180000, dmg: 12500, accuracy: 0.82, durability: 950 },
  { id: "cosmic_bow", name: "Cosmic Bow", tier: "Cosmic", price: 155000, dmg: 9800, accuracy: 0.94, durability: 1050 }
];

export const SHOP_ITEMS = [
  ...WEAPONS,
  { id: "small_heal", name: "Small Healing Potion 🧪", tier: "Item", price: 30, description: "Menyembuhkan luka kecil di pertempuran." },
  { id: "large_heal", name: "Large Healing Potion 🧪", tier: "Item", price: 80, description: "Menyembuhkan luka berat di pertempuran." },
  { id: "elixir_str", name: "Elixir of Strength 🧪", tier: "Item", price: 150, description: "Meningkatkan daya serang dasar secara permanen." },
  { id: "xp_scroll", name: "XP Booster Scroll 📜", tier: "Item", price: 200, description: "Memberikan peningkatan bonus XP saat berburu." },
  { id: "coin_mult", name: "Coin Multiplier Coin 🪙", tier: "Item", price: 250, description: "Menggandakan perolehan Cowoncy dalam 5 menit berikutnya." },
  { id: "bronze_crate", name: "Bronze Crate 📦", tier: "Item", price: 80, description: "Berisi senjata Bronze acak." },
  { id: "silver_crate", name: "Silver Crate 📦", tier: "Item", price: 800, description: "Berisi senjata Silver acak." },
  { id: "gold_crate", name: "Gold Crate 📦", tier: "Item", price: 2000, description: "Berisi senjata Gold acak." },
  { id: "diamond_crate", name: "Diamond Crate 📦", tier: "Item", price: 15000, description: "Berisi senjata Diamond acak." },
  { id: "mythic_crate", name: "Mythic Crate 📦", tier: "Item", price: 60000, description: "Berisi senjata Mythic acak." },
  { id: "crate", name: "Animal Crate 📦", tier: "Item", price: 200, description: "Berisi hewan acak (berpeluang mendapat Epic/Mythic)." },
  { id: "lootbox", name: "Lootbox 🎁", tier: "Item", price: 150, description: "Berisi senjata acak atau Cowoncy dalam jumlah besar." }
];
